baseURL = 'https://diyansantoso.github.io'
languageCode = 'en-us'
title = 'Diyan Santoso'
theme = "paper"

disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'diyansantoso'                 # github.com/YOUR_GITHUB_ID
  instagram = 'diyan_santoso'           # instagram.com/YOUR_INSTAGRAM_ID

  # home page profile
  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Diyan Santoso'
  bio = 'Pasti Bisa.'

                      